### ISSUE TITLE
pjax calls

### ISSUE THREAD

**Issue by paskuale75** [thtmorais/yii2-pace#1]
how does it deal with pjax calls ? I add it on main layout, but when I click on a button, do you always wait a few seconds before leaving? Could it be because I have chained calls between them ?

Thanks

**Comment by thtmorais** [comment]
Hello @paskuale75, currently any request that is made, the widget will be called, be it the loading of a page or an AJAX request.

You can read more about pace-js [here](https://codebyzach.github.io/pace/).

And any improvements are gladly accepted with an MR!

**Comment by paskuale75** [comment]
Thanks for reply, It could be a problem of calls made in succession, it seems to take only the last one.
