### ISSUE TITLE
two-factor auth

### ISSUE THREAD

**Issue by paskuale75** [thtmorais/yii2-pace#2]
Hi @thtmorais can u pass auth to 2factor type ? I forked it and I can't push with old authentication method, thanks

**Comment by thtmorais** [comment]
Sorry, i can't because i don't use android or iOS phone and  auth2factor in phone number in my country it's disabled.

**Comment by paskuale75** [comment]
[solved]
https://stackoverflow.com/questions/17659206/git-push-results-in-authentication-failed
thanks to [rc0r](https://stackoverflow.com/users/3155236/rc0r)
